apiVersion: v1
kind: Pod
metadata:
 name: first-pod1
spec:
 containers:
 - name: c1
   image: ubuntu
   command: ["sh", "-c", "echo 'hello aditya' > /data/msg && sleep 4000"]
   volumeMounts:
   - name: shared-data
     mountPath: /data
 - name: c2
   image: ubuntu
   command: ["sh", "-c", " cat > /data/msg && sleep 4000"]
   volumeMounts:
   - name: shared-data
     mountPath: /data
 volumes:
 - name: shared-data
   emptyDir: {}
