apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: dev
spec:
  containers:
  - name: c01
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello kapil; sleep 5; done"]
    volumeMounts:
    - name: testing
      mountPath: "/tmp/config"
  volumes:
  - name: testing
    configMap:
      name: mymap
      items:
      - key: sample.conf
        path: sample.conf
