apiVersion: v1
kind: Pod
metadata: 
 name: pod01

spec:
  containers:
  - name: c0011
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo hello kapil; sleep 5;done"]
    volumeMounts:
    - mountPath: "/var/www/html"
      name: mypod

  volumes:
  - name: mypod
    persistentVolumeClaim:
      claimName: claim1
