apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
spec:
  capacity:
    storage: 2Gi            # Size of the nfs-server volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    path: /nfsdata          # path on which k8-n-4 exposes the nfs mount
    server: 172.31.32.91
